name: dart_task_manager
description: A task_manager manager application using MCP (Model Context Protocol).
version: 1.0.0
# repository: https://github.com/my_org/my_repo
license: MIT

environment:
  sdk: ^3.8.0

dependencies:
  mcp_server: ^1.0.2
  mcp_client: ^1.0.1
  uuid: ^4.0.0
  dio: ^5.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
